site_name: finmc
theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange

      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: deep orange

      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode


  features:
    - navigation.tabs

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [finmc]
          options:
            members_order: source
            show_root_toc_entry: false
            show_source: false
            show_bases: false

# extra_css:
#   - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 'Home':
    - 'index.md'
    - 'dataset.md'
    - 'rates.md'
    - 'forwards.md'
    - 'utilities.md'
    - 'calculators.md'
  - 'Models':
    - 'models/heston.md'
    - 'models/hullwhite.md'
    - 'models/localvol.md'
    - 'models/api.md'
